TomasHorvath.BlogEngine.Frontend/ViewModels/BlogPostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TomasHorvath.BlogEngine.Frontend.ViewModels
{
	public class BlogPostViewModel
	{
		public Guid Id { get; set; }
		public string Perex { get; set; }
		public string Headline { get; set; }
		public string Content { get; set; }
		public string Keyword { get; set; }
		public string Description { get; set; }
		public DateTime DateOfPublished { get; set; }
		public string AuthorName { get; set; }
		
	}
}

TomasHorvath.BlogEngine.Frontend/ViewModels/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TomasHorvath.BlogEngine.Frontend.ViewModels
{
	public class CommentViewModel
	{
		Guid BlogPostId { get; set; }
		Guid Id { get; set; }

	}
}

TomasHorvath.BlogEngine.Frontend/Controllers/BlogPostController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TomasHorvath.BlogEngine.Domain;

namespace TomasHorvath.BlogEngine.Frontend.Controllers
{
	public class BlogPostController : Controller
	{
		private readonly BL.Interface.IBlogPostService _blogService;
		public BlogPostController(BL.Interface.IBlogPostService blog)
		{
			_blogService = blog;
		}

		public PartialViewResult Index(int? pageSize, int? page)
		{
			ViewBag.Root = ConfigurationManager.AppSettings["Root"];
			var PageNumber = (page ?? 0);
			var PageSize = (pageSize ?? 10);
			var totalRowCount = 0;

			var blogPosts = _blogService.GetByPage(PageSize, PageNumber, out totalRowCount);
			return PartialView(blogPosts);
		}

		public ActionResult Detail(Guid Id)
		{
			try
			{
				var model = _blogService.GetById(Id);
				return View(model);
			}
			catch (Exception ex)
			{
				return HttpNotFound();
			}
		}
	}
}

TomasHorvath.BlogEngine.Frontend/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TomasHorvath.BlogEngine.Frontend.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
    }
}

TomasHorvath.BlogEngine.Frontend/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TomasHorvath.BlogEngine.Frontend.Controllers
{
	public class HomeController : Controller
	{
		// GET: Home
		public ActionResult Index()
		{
			ViewBag.Title = "Tomáš Horváth | .NET Developer";
			ViewBag.Keywords = "Tomáš Horváth,.NET,CORE,MVC,DDD";
			ViewBag.Description = "Tomáš Horváth developer blog";


			return View();
		}
	}
}

TomasHorvath.BlogEngine.Frontend/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TomasHorvath.BlogEngine.Frontend.Controllers
{
	public class PageController : Controller
	{
		private readonly BL.Interface.IPageService _pageService;

		public PageController(BL.Interface.IPageService pageService)
		{
			_pageService = pageService;
		}
		public ActionResult Index()
		{
			return View();
		}

		[ChildActionOnly]
		public PartialViewResult Menu()
		{
			var model = _pageService.GetMenu();
			return PartialView(model);
		}
	}
}

TomasHorvath.BlogEngine.Frontend/Views/BlogPost/Detail.cshtml
@model TomasHorvath.BlogEngine.Domain.DTO.BlogPost.BlogPostDetailDTO
@{
  ViewBag.Title = Model.Headline;
  Layout = "~/Views/Shared/_LayoutDetail.cshtml";
}


<section id="blog-item">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1>@Model.Headline</h1>
				<p>
					<strong>@Model.Perex</strong>
				</p>
				<p>
					@Model.Content
				</p>
			</div>
			

		</div><!--End row -->


	</div><!--End container -->
</section>

TomasHorvath.BlogEngine.Frontend/Views/BlogPost/Index.cshtml
@{
  string root = ViewBag.Root;

 }
@model IPagedList<TomasHorvath.BlogEngine.Domain.DTO.BlogPost.BlogPostPreviewDto>
<section id="blog">
	<div class="container">
		<input type="hidden" name="filterContext" id="filterContext" value="@Model.FilterJson">
		<div class="row">
		@foreach (TomasHorvath.BlogEngine.Domain.DTO.BlogPost.BlogPostPreviewDto article in Model)
		{
		<div class="col-sm-6">
			<h1>@article.Headline</h1>
			<p>
				@article.Perex
			</p>
			<a href="@root@article.Url" class="btn btn-primary">Celý článek</a>
		</div>
		}

		</div><!--End row -->
		<div class="row">
			<div class="col-sm-12 ">
				<!-- Vouchers -->
				@if (Model.EndPage > 1)
				{
				<ul class="pagination">
					@if (Model.PageIndex > 1)
					{
					<li>
						<a class="datapage" data-page="1" href="#">First</a>
					</li>
					<li>
						<a class="datapage" data-page="@(Model.PageIndex - 1)" href="~/Home/Index?page=@(Model.PageIndex - 1)">Previous</a>
					</li>
					}

					@for (var page = Model.StartPage; page <= Model.EndPage; page++)
					{
					<li class="@(page == Model.PageIndex ? "active" : "")">
						<a class="datapage" data-page="@page" href="~/Home/Index?page=@page">@page</a>
					</li>    }

					@if (Model.PageIndex < Model.TotalPages)
					{
					<li>
						<a class="datapage" data-page="@(Model.PageIndex + 1)" href="~/Home/Index?page=@(Model.PageIndex + 1)">Next</a>
					</li>
					<li>
						<a class="datapage" data-page="@(Model.TotalPages)" href="~/Home/Index?page=@(Model.TotalPages)">Last</a>
					</li>
					}
				</ul>
				}


			</div>
		</div>

	</div><!--End container -->
</section>

TomasHorvath.BlogEngine.Frontend/Views/Home/Index.cshtml
@{
  ViewBag.Title = "Index";
  Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- ==============================================
   HEADER
   =============================================== -->
<header id="home" class="jumbotron">

	<div class="container">

		<div class="message-box clearfix">

			<div class="left-col">
				<p>I AM <span>.NET</span></p>
			</div>

			<div class="right-col flexslider home-slider" style="z-index:1;">

				<ul class="slides">

					<li><p>Developer</p></li>

					<li><p>Enthusiast</p></li>

					<li><p>Trainer</p></li>

				</ul>

			</div><!--End home-slider -->

		</div><!--End message-box -->

	</div><!--End container -->

</header><!--End header -->


<section id="about">

	<div class="container">

		<div class="row">
			<div class="col-sm-4 col-sm-offset-1 scrollimation fade-right">
				<img class="img-responsive img-circle img-center" src="http://thsoftware.cz/Content/assets/about.jpg" alt="">
			</div>
			<div class="col-sm-6 col-sm-offset-1 scrollimation fade-left">
				<h1>Tomáš Horváth</h1>
				<h2>IT Konzultant &amp; .NET DEVELOPER </h2>
				<p>
					Jsem vývojář a konzultant z Jihočeského kraje, který se zajímá o .NET a agilní techniky vývoje.
					V současné době se nejvíce zaměřuji na : #KISS , #DRY , #SOLID , #DDD , #CQRS
					<br /><br />
				</p>

			</div>
		</div><!--End row -->

	</div><!--End container -->
</section>
<div id="blog-section">
	@Html.Action("Index", "BlogPost", new { pageSize = 10 })
</div>
@section scripts {

	<script>
	function Set(context) {

            var page = context.data("page");
            //var obj = JSON.parse($("#filterContext").val());
            //obj.CurrentPage = page;
            var url = "@Url.Action("Index", "BlogPost")" + "?page="+page;

            $.ajax({
                url: url,
                type: 'GET',
                //data: JSON.stringify(obj),
                beforeSend: function () {
                    //AjaxBegin();
                },
                contentType: 'application/json; charset=utf-8',
                error: function (xhr) {
                    alert('Error: ' + xhr.statusText);
                },
                success: function (result) {

					//$("#blog-section").empty();
					$("#blog-section").html(result);
                  

                },
                async: false
            });
        }

        function SetPaging() {

            $(".datapage").unbind("click");
            $(".datapage").click(function (event) {
                event.preventDefault();
               var context = $(this);
                Set(context);

            });


	}

		$(document).ready(function () {
			SetPaging();
		});
	</script>

}

TomasHorvath.BlogEngine.Frontend/Views/Page/Menu.cshtml
@model IEnumerable<TomasHorvath.BlogEngine.Domain.DTO.MenuItemDto>

<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<ul class="nav navbar-nav navbar-right">
		@foreach (TomasHorvath.BlogEngine.Domain.DTO.MenuItemDto menu in Model)
		{
		<li>
			<a href="@menu.Url">@menu.Name</a>
		</li>
		}
	</ul>
</div>

TomasHorvath.BlogEngine.Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-US" class="no-js">
<head>

	<!-- ==============================================
	Title and Meta Tags
	=============================================== -->
	<meta charset="utf-8">
	
	<title>@ViewBag.Title</title>
	<meta name="keywords" content="@ViewBag.Keywords" />
	<meta name="description" content="@ViewBag.Description" />

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<!-- ==============================================
	Favicons
	=============================================== -->
	<link rel="shortcut icon" href="~/Content/assets/favicon.ico">
	<link rel="apple-touch-icon" href="~/Content/assets/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="~/Content/assets/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="~/Content/assets/apple-touch-icon-114x114.png">

	<!-- ==============================================
	CSS
	=============================================== -->
	<link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/Content/css/flexslider.css">
	<link rel="stylesheet" href="~/Content/css/font-awesome.min.css">
	<link rel="stylesheet" href="~/Content/css/designr-theme-cyan.css">


	<!-- ==============================================
	Fonts
	=============================================== -->
	<!--<link href='http://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic,900' rel='stylesheet' type='text/css'> -->
	<link href='http://fonts.googleapis.com/css?family=Oxygen:400,300' rel='stylesheet' type='text/css'>
	<!-- ==============================================
	JS
	=============================================== -->
	<!--[if lt IE 9]>
		<script src="js/respond.min.js"></script>
	<![endif]-->

	<script type="text/javascript" src="~/Content/js/libs/modernizr.min.js"></script>


</head>

<body data-spy="scroll" data-target="#main-nav" data-offset="200">

	<!--=== PAGE PRELOADER ===-->
	<!--<div id="page-loader"><span class="page-loader-gif"></span></div>-->
	<!-- ==============================================
	MAIN NAV
	=============================================== -->
	@Html.Partial("_navigation")
	<!--End main-nav -->

	@RenderBody()
	<!-- ==============================================
	FOOTER
	=============================================== -->
	<footer id="main-footer">

		<div class="container">

			<div class="row">

				<div class="col-sm-6 left-col">
					<h1 class="small-logo">Tomáš Horváth<br /><span>IT Consultant & .NET DEVELOPER</span></h1>
					<ul class="footer-nav">
						<li><a class="scrollto" href="#home">Úvod</a></li>
						<li><a class="scrollto" href="#services">Služby</a></li>
						<li><a class="scrollto" href="#portfolio">Portfolio</a></li>
						<li><a class="scrollto" href="#contact">Kontakt</a></li>
					</ul>
					<p>&copy;Copyright 2015 / All Rights Reserved</p>
				</div>

				<div class="col-sm-6 right-col">
					<h4>Kdo jsem ?</h4>
					<p>Jsem IT konzultant a vývojář, který se rád učí a zajíma se o nové technologie. Zaroveň jsem věčný optimista v životě ,ale velký realista v analýzách systémů a navrhování.</p>
				</div>

			</div><!-- End row -->

		</div><!-- End container -->

	</footer><!-- End footer -->
	<!-- ==============================================
	SCRIPTS
	=============================================== -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="js/libs/jquery-1.9.1.min.js">\x3C/script>')</script>

	<script src="~/Content/js/libs/bootstrap.min.js"></script>
	<script src='~/Content/js/jquery.scrollto.js'></script>
	<script src='~/Content/js/jquery.flexslider.min.js'></script>
	<script src='~/Content/js/twitterFetcher_v10_min.js'></script>
	<script src='~/Content/js/jquery.masonry.min.js'></script>
	<script src="~/Content/js/waypoints.min.js"></script>
	<script src="~/Content/js/jquery.easypiechart.min.js"></script>
	<script src="~/Content/js/jquery.backstretch.min.js"></script>
	<script src="~/Content/js/contact.js"></script>
	<script src="~/Content/js/designr.js"></script>
</body>

</html>

TomasHorvath.BlogEngine.Frontend/Views/Shared/_LayoutDetail.cshtml
<!DOCTYPE html>
<html lang="en-US" class="no-js">
<head>

	<!-- ==============================================
	Title and Meta Tags
	=============================================== -->
	<meta charset="utf-8">

	<title>@ViewBag.Title</title>
	<meta name="keywords" content="@ViewBag.Keywords" />
	<meta name="description" content="@ViewBag.Description" />

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<!-- ==============================================
	Favicons
	=============================================== -->
	<link rel="shortcut icon" href="~/Content/assets/favicon.ico">
	<link rel="apple-touch-icon" href="~/Content/assets/apple-touch-icon.png">
	<link rel="apple-touch-icon" sizes="72x72" href="~/Content/assets/apple-touch-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="114x114" href="~/Content/assets/apple-touch-icon-114x114.png">

	<!-- ==============================================
	CSS
	=============================================== -->
	<link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/Content/css/flexslider.css">
	<link rel="stylesheet" href="~/Content/css/font-awesome.min.css">
	<link rel="stylesheet" href="~/Content/css/designr-theme-cyan.css">


	<!-- ==============================================
	Fonts
	=============================================== -->
	<!--<link href='http://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic,900' rel='stylesheet' type='text/css'> -->
	<link href='http://fonts.googleapis.com/css?family=Oxygen:400,300' rel='stylesheet' type='text/css'>
	<!-- ==============================================
	JS
	=============================================== -->
	<!--[if lt IE 9]>
		<script src="js/respond.min.js"></script>
	<![endif]-->

	<script type="text/javascript" src="~/Content/js/libs/modernizr.min.js"></script>


</head>

<body data-spy="scroll" data-target="#main-nav" data-offset="0">

	<!--=== PAGE PRELOADER ===-->
	<!--<div id="page-loader"><span class="page-loader-gif"></span></div>-->
	<!-- ==============================================
	MAIN NAV
	=============================================== -->
	@Html.Partial("_navigation")
	<!--End main-nav -->

	@RenderBody()
	<!-- ==============================================
	FOOTER
	=============================================== -->
	<section id="#contact">
		<footer id="main-footer">

			<div class="container">

				<div class="row">

					<div class="col-sm-6 left-col">
						<h1 class="small-logo">Tomáš Horváth<br /><span>IT Consultant & .NET DEVELOPER</span></h1>
						<ul class="footer-nav">
							<li><a class="scrollto" href="#home">Úvod</a></li>
							<li><a class="scrollto" href="#services">Služby</a></li>
							<li><a class="scrollto" href="#portfolio">Portfolio</a></li>
							<li><a class="scrollto" href="#contact">Kontakt</a></li>
						</ul>
						<p>&copy;Copyright 2015 / All Rights Reserved</p>
					</div>

					<div class="col-sm-6 right-col">
						<h4>Kdo jsem ?</h4>
						<p>Jsem IT konzultant a vývojář, který se rád učí a zajíma se o nové technologie. Zaroveň jsem věčný optimista v životě ,ale velký realista v analýzách systémů a navrhování.</p>
					</div>

				</div><!-- End row -->

			</div><!-- End container -->

		</footer><!-- End footer -->
	</section>
	<!-- ==============================================
	SCRIPTS
	=============================================== -->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
	<script>window.jQuery || document.write('<script src="js/libs/jquery-1.9.1.min.js">\x3C/script>')</script>

	<script src="~/Content/js/libs/bootstrap.min.js"></script>
	<script src='~/Content/js/jquery.scrollto.js'></script>
	<script src='~/Content/js/jquery.flexslider.min.js'></script>
	<script src='~/Content/js/twitterFetcher_v10_min.js'></script>
	<script src='~/Content/js/jquery.masonry.min.js'></script>
	<script src="~/Content/js/waypoints.min.js"></script>
	<script src="~/Content/js/jquery.easypiechart.min.js"></script>
	<script src="~/Content/js/jquery.backstretch.min.js"></script>
	<script src="~/Content/js/contact.js"></script>
	<script src="~/Content/js/designr.js"></script>

	@RenderSection("scripts", false)

</body>

</html>

TomasHorvath.BlogEngine.Frontend/Views/Shared/_footer.cshtml
	<!-- Footer -->
<footer>
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<ul class="list-inline text-center">
					<li>
						<a href="#">
							<span class="fa-stack fa-lg">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
							</span>
						</a>
					</li>
					<li>
						<a href="#">
							<span class="fa-stack fa-lg">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
							</span>
						</a>
					</li>
					<li>
						<a href="#">
							<span class="fa-stack fa-lg">
								<i class="fa fa-circle fa-stack-2x"></i>
								<i class="fa fa-github fa-stack-1x fa-inverse"></i>
							</span>
						</a>
					</li>
				</ul>
				<p class="copyright text-muted">Copyright &copy; Your Website 2016</p>
			</div>
		</div>
	</div>
</footer>

TomasHorvath.BlogEngine.Frontend/Views/Shared/_navigation.cshtml
@*<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				Menu <i class="fa fa-bars"></i>
			</button>
			<a class="navbar-brand" href="index.html">@Html.Setting("BrandName")</a>
		</div>
		<!-- menu page -->
		@Html.Action("Menu", "Page")
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container -->
</nav>*@



<div id="main-nav" class="navbar navbar-fixed-top">
	<div class="container">

		<div class="navbar-header">

			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#site-nav">
				<span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
			</button>

			<!-- ======= LOGO ========-->
			<a class="navbar-brand scrollto" href="#home">Tomáš Horváth<br><span>.NET DEVELOPER</span></a>
			<!-- <a class="navbar-brand scrollto ir-logo" href="#">JOHN DOE<br><span>UI Designer</span></a> -->

		</div>

		<div id="site-nav" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="sr-only">
					<a href="#home" class="scrollto">Home</a>
				</li>
				<li>
					<a href="#about" class="scrollto">O mně</a>
				</li>
				<li>
					<a href="#nopcommerce" >NopCommerce</a>
				</li>
				
				<li>
					<a href="#blog" class="scrollto">Blog</a>
				</li>
				<li>
					<a href="https://github.com/TomasHorvath" target="_blank">GitHub</a>
				</li>

				<li>
					<a href="#contact" class="scrollto">Kontakt</a>
				</li>


			</ul>
		</div><!--End navbar-collapse -->

	</div><!--End container -->

</div>